name = "TrapezoidalRule"
uuid = "3e03e466-848d-4814-b912-b7d775a3c99c"
authors = ["Nora <nora-berthold@gmx.de>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
